### ISSUE TITLE
navigator.notification.alert does not work at iOS

### ISSUE THREAD

**Issue by ryuheimat** [apache/cordova-plugin-dialogs#112]
I captured [video](https://www.useloom.com/share/1356cc10f1cf4ab4ad1f72b54fcf1055) for the issue.
Cordova version: 8.0.0
OS: iOS (The alert works fine at the android device)

**Comment by magancete** [comment]
I have the same issue any idea?

**Comment by matb33** [comment]
It's because this line hasn't been updated for Cordova 7 yet:
https://github.com/apache/cordova-plugin-dialogs/blob/master/plugin.xml#L38
The `target` path needs to be `app/src/main/res/xml/config.xml`

I falsely assumed that any Cordova-supported plugin would have been updated as part of this breaking change (https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html). This plugin appears to have been overlooked. Sadly, other Cordova-supported plugins are in the same boat, e.g. https://github.com/apache/cordova-plugin-device/blob/master/plugin.xml#L39

**Comment by ryuheimat** [comment]
@matb33 this issue is opened for iOS, not for android. it works fine on android device.

**Comment by ryuheimat** [comment]
I tried setting config.xml file, but same [issue](https://www.useloom.com/share/1356cc10f1cf4ab4ad1f72b54fcf1055).

**Comment by janpio** [comment]
@matb33 Feel free to create a PR with these changes for all plugins that are still affected - we would be happy to accept any changes we overlooked back then.

**Comment by janpio** [comment]
@ryuheimat @magancete So you are reporting that the `alert` dialog does not appear when it is triggered but only after you leave and re-enter the app - correct?

Please post all you versions:
Cordova CLI, Cordova iOS, plugin, iOS and iOS device you are testing on. 
Can this be reproduced in the simulator as well?

**Comment by ryuheimat** [comment]
Cordova: ^8.1.2
Cordova iOS: ^4.5.5
plugins: [phonegap-parse-plugin](https://github.com/grrrian/phonegap-parse-plugin), cordova-plugin-crosswalk-webview(^2.4.0), cordova-plugin-geolocation(^1.0.1), cordova-plugin-whitelist(^1.3.3)

I tested on both simulator and device, however results on all devices were same.
Obviously, I tested on iPhone6 Simulator and iPhone7 device.

**Comment by janpio** [comment]
What iOS version were the device and simulator running?

Can you create a reproduction project that _only_ includes this plugin and minimal code to reproduce the problem and put it on Github please?

**Comment by jcesarmobile** [comment]
you have to add `gap:` to your Content-Security-Policy meta tag

**Comment by jcesarmobile** [comment]
Closing as every time I've seen this problem was because of missing `gap:` in the index.html and there was no response after I asked if it was present. So I'll assume it wasn't
